name: CI

on:
  push:
    branches:
      - main
      - feature/*
      - migration/*
      - hotfix/*
  pull_request:
    branches: 
      - main
      - feature/*
      - migration/*
      - hotfix/*

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:

  build:

    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.7.0"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Setup CMake
        uses: lukka/get-cmake@v3.23.2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Depedendencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Publish to Github Release
        if: github.ref == 'refs/heads/main'
        run: npm run upload
        env:
          PREBUILD_TOKEN: ${{ secrets.PREBUILD_TOKEN }}

  deploy:

    name: Deploy

    needs: [build]

    runs-on: 'ubuntu-latest'

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.7.0"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Depedendencies
        run: npm ci

      - name: Deploy to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          access: "public"
          token: ${{ secrets.NPM_TOKEN }}