name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:

  build:

    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.7.0"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Depedendencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Publish to AWS
        run: npm run pregyp
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:

    name: Deploy

    needs: [build]

    runs-on: 'ubuntu-latest'

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.7.0"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Depedendencies
        run: npm ci

      - name: Deploy to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          access: "public"
          token: ${{ secrets.NPM_TOKEN }}